### PR TITLE
PHP XDebug extension installation suggestion

### PR DESCRIPTION
**Pull request by spam312sn**
What about adding XDebug to container for code coverage tests with PHPUnit or Codeception?

### CODE REVIEW

**Comment by stepansib** [comment]
Great.

**Comment by stepansib** [comment]
@spam312sn My apoligize, dockerhub was stuck with no reason.
I triggered build manually, image will be compiled in a half an hour https://hub.docker.com/r/stepansib/php-symfony-oro/

**Comment by spam312sn** [comment]
@stepansib Please do not apologize - I'm in no hurry. Just the last few days I have been using your container and decided to supplement with those things that seemed necessary for future builds

**Comment by stepansib** [comment]
@spam312sn thank you. You can check out my docker-compose environment that use this container - https://github.com/stepansib/sf-oro-docker

**Pull request merged**
